name: PR Compare
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
    paths:
      - models/**
      - seeds/**
      - tests/**

jobs:
  piperider-compare:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    - name: set profiles
      run: |
        mkdir ~/.dbt
        cat << EOF > ~/.dbt/profiles.yml
        my_new_project:
          target: default
          outputs:
            default:
              type:      bigquery
              database:  dbt-demo
              schema:    dbt-demo-396606
        EOF
        cat ~/.dbt/profiles.yml

    - name: PipeRider Compare
      uses: InfuseAI/piperider-compare-action@v1
      env: 
        DBT_PROFILES_DIR: ${{ github.workspace }} 
      with:
        cloud_api_token: ${{ secrets.PIPERIDER_CLOUD_TOKEN_ID }}
        cloud_project: ${{ secrets.PIPERIDER_API_PROJECT }}
        upload: true
        share: true