name: PR Compare
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
    paths:
      - models/**
      - seeds/**
      - tests/**

jobs:
  piperider-compare:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    - name: set profiles
      run: |
        mkdir ~/.dbt
        cat << EOF > ~/.dbt/profiles.yml
        default:
          target: bigquery
          outputs:
            bigquery:
              type: bigquery
              method: service-account
              keyfile: ${{ secrets.DBT_GOOGLE_KEYFILE }}
              project: dbt-demo-396606
              dataset: marts
              threads: 4
        EOF
        cat ~/.dbt/profiles.yml

    - name: PipeRider Compare
      uses: InfuseAI/piperider-compare-action@v1
      env: 
        DBT_PROFILES_DIR: ${{ github.workspace }} 
      with:
        cloud_api_token: ${{ secrets.PIPERIDER_CLOUD_TOKEN_ID }}
        cloud_project: ${{ secrets.PIPERIDER_API_PROJECT }}
        upload: true
        share: true